# Generated by Django 5.2.1 on 2025-09-02 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                ("ai_summary", models.TextField()),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="study_notes", to="studies.studygroup"
                    ),
                ),
            ],
            options={
                "db_table": "study_notes",
            },
        ),
        migrations.CreateModel(
            name="StudyNoteAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("file_url", models.URLField(max_length=255)),
                ("file_name", models.CharField(max_length=50)),
                (
                    "study_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="study_notes.studynote",
                    ),
                ),
            ],
            options={
                "db_table": "study_note_attachments",
            },
        ),
        migrations.CreateModel(
            name="StudyNoteImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("img_url", models.URLField(max_length=255)),
                (
                    "study_note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="images", to="study_notes.studynote"
                    ),
                ),
            ],
            options={
                "db_table": "study_note_images",
            },
        ),
    ]
