# Generated by Django 5.2.1 on 2025-09-02 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study_notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studynote",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="studynote",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="studynoteattachment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="studynoteattachment",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="studynoteimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="studynoteimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
    ]
