# Generated by Django 5.2.1 on 2025-09-02 04:47

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lectures", "0003_alter_lecture_unique_together"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("is_leader", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "group_members",
            },
        ),
        migrations.CreateModel(
            name="StudyGroup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("name", models.CharField(max_length=20)),
                ("introduction", models.CharField(max_length=500, null=True)),
                (
                    "max_headcount",
                    models.SmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("profile_img_url", models.URLField(blank=True, max_length=255, null=True)),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "대기중"), ("ONGOING", "진행중"), ("ENDED", "종료됨")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("members", models.ManyToManyField(through="studies.GroupMember", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "db_table": "study_groups",
            },
        ),
        migrations.AddField(
            model_name="groupmember",
            name="study_group",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.studygroup"),
        ),
        migrations.CreateModel(
            name="StudyLecture",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "study_group_id", "lecture_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("lecture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.lecture")),
                (
                    "study_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.studygroup"),
                ),
            ],
            options={
                "db_table": "study_lectures",
            },
        ),
        migrations.AddField(
            model_name="studygroup",
            name="lectures",
            field=models.ManyToManyField(through="studies.StudyLecture", to="lectures.lecture"),
        ),
        migrations.AlterUniqueTogether(
            name="groupmember",
            unique_together={("study_group_id", "user_id")},
        ),
        migrations.CreateModel(
            name="StudyReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "star_rating",
                    models.IntegerField(
                        choices=[
                            (5, "Five Stars"),
                            (4, "Four Stars"),
                            (3, "Three Stars"),
                            (2, "Two Stars"),
                            (1, "One Star"),
                        ],
                        verbose_name="평점",
                    ),
                ),
                ("content", models.CharField(max_length=500, verbose_name="리뷰 내용")),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="studies.studygroup"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "reviews",
                "unique_together": {("user", "study_group")},
            },
        ),
    ]
