# Generated by Django 5.2.1 on 2025-09-02 05:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmember",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="groupmember",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="studygroup",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUID", unique=True),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="studylecture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="studyreview",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="studyreview",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
    ]
