# Generated by Django 5.2.1 on 2025-09-02 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSchedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("title", models.CharField(max_length=50)),
                ("objective", models.CharField(max_length=255)),
                ("session_date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "study_group",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.studygroup"),
                ),
            ],
            options={
                "db_table": "group_schedules",
            },
        ),
        migrations.CreateModel(
            name="ScheduleParticipant",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "schedule_id", "member_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="studies.groupmember")),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="study_group_schedules.groupschedule"
                    ),
                ),
            ],
            options={
                "db_table": "schedule_participants",
            },
        ),
        migrations.AddField(
            model_name="groupschedule",
            name="participants",
            field=models.ManyToManyField(through="study_group_schedules.ScheduleParticipant", to="studies.groupmember"),
        ),
    ]
