# Generated by Django 5.2.1 on 2025-09-02 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_alter_groupmember_created_at_and_more"),
        ("study_group_schedules", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupschedule",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="groupschedule",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="ScheduleParticipant",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="ScheduleParticipant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
    ]
