# Generated by Django 5.2.1 on 2025-09-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studies", "0002_alter_groupmember_created_at_and_more"),
        ("study_group_schedules", "0002_alter_groupschedule_created_at_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(fields=["study_group", "session_date"], name="group_sched_study_g_117aff_idx"),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(fields=["session_date"], name="group_sched_session_69a56d_idx"),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(
                fields=["study_group", "session_date", "start_time"], name="group_sched_study_g_6320cb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(fields=["-created_at"], name="group_sched_created_a16b53_idx"),
        ),
        migrations.AddIndex(
            model_name="groupschedule",
            index=models.Index(
                fields=["study_group", "session_date", "-created_at"], name="group_sched_study_g_6e707a_idx"
            ),
        ),
    ]
