# Generated by Django 5.2.1 on 2025-09-01 08:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="email address")),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("nickname", models.CharField(max_length=10, unique=True, verbose_name="닉네임")),
                ("phone_number", models.CharField(max_length=20, unique=True, verbose_name="휴대폰 번호")),
                ("gender", models.CharField(max_length=6, verbose_name="성별")),
                ("birthday", models.DateField(verbose_name="생일")),
                (
                    "profile_img_url",
                    models.URLField(
                        blank=True,
                        help_text="유저 프로필 이미지",
                        max_length=255,
                        null=True,
                        verbose_name="프로필 이미지",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="계정활성화 여부")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프 여부")),
                ("is_superuser", models.BooleanField(default=False, verbose_name="슈퍼 유저 여부")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("id", models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("KAKAO", "카카오"), ("NAVER", "네이버")],
                        max_length=10,
                        verbose_name="소셜 로그인 제공 업체",
                    ),
                ),
                ("provider_id", models.CharField(max_length=255, verbose_name="소셜 로그인 업체 고유 ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생설 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 일시")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="유저"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdrwals",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NO_LONGER_NEEDED", "서비스 이용할 시간이 없음"),
                            ("LACK_OF_INTEREST", "관심이 사라짐"),
                            ("TOO_DIFFICULT", "서비스를 이용하기가 너무 어려움"),
                            ("FOUND_BETTER_SERVICE", "더 좋은 대안을 찾음"),
                            ("PRIVACY_CONCERNS", "개인정보/보안/우려"),
                            ("POOR_SERVICE_QUALITY", "서비스 품질 불만"),
                            ("TECHNICAL_ISSUES", "기술적문제(버그 등)"),
                            ("LACK_OF_CONTENT", "원하는 콘텐츠나 기능의 부족"),
                            ("OTHER", "기타"),
                        ],
                        max_length=30,
                        verbose_name="탈퇴 사유",
                    ),
                ),
                ("reason_detail", models.DateField(verbose_name="구체적인 탈퇴 사유")),
                ("due_date", models.DateField(verbose_name="계정 삭제 예정일")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="유저"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
