# Generated by Django 5.2.1 on 2025-09-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                ("email", models.EmailField(max_length=255, unique=True, verbose_name="email address")),
                ("hashed_password", models.CharField(max_length=130, verbose_name="해시된 비밀번호")),
                ("name", models.CharField(max_length=30, verbose_name="이름")),
                ("nickname", models.CharField(max_length=10, unique=True, verbose_name="닉네임")),
                ("phone_number", models.CharField(max_length=20, unique=True, verbose_name="휴대폰 번호")),
                ("gender", models.CharField(max_length=6, verbose_name="성별")),
                ("birthday", models.DateField(verbose_name="생일")),
                (
                    "profile_img_url",
                    models.URLField(
                        blank=True,
                        help_text="유저 프로필 이미지",
                        max_length=255,
                        null=True,
                        verbose_name="프로필 이미지",
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="계정활성화 여부")),
                ("is_staff", models.BooleanField(default=False, verbose_name="스태프 여부")),
                ("is_superuser", models.BooleanField(default=False, verbose_name="슈퍼 유저 여부")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
