# Generated by Django 5.2.1 on 2025-09-02 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrwals",
            name="reason_detail",
            field=models.CharField(max_length=500, verbose_name="구체적인 탈퇴 사유"),
        ),
    ]
