# Generated by Django 5.2.1 on 2025-09-01 06:19

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialUser",
            fields=[
                ("id", models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                (
                    "provider",
                    models.CharField(
                        choices=[("KAKAO", "카카오"), ("NAVER", "네이버")],
                        max_length=10,
                        verbose_name="소셜 로그인 제공 업체",
                    ),
                ),
                ("provider_id", models.CharField(max_length=255, verbose_name="소셜 로그인 업체 고유 ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생설 일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정 일시")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="유저"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Withdrwals",
            fields=[
                ("id", models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("NO_LONGER_NEEDED", "서비스 이용할 시간이 없음"),
                            ("LACK_OF_INTEREST", "관심이 사라짐"),
                            ("TOO_DIFFICULT", "서비스를 이용하기가 너무 어려움"),
                            ("FOUND_BETTER_SERVICE", "더 좋은 대안을 찾음"),
                            ("PRIVACY_CONCERNS", "개인정보/보안/우려"),
                            ("POOR_SERVICE_QUALITY", "서비스 품질 불만"),
                            ("TECHNICAL_ISSUES", "기술적문제(버그 등)"),
                            ("LACK_OF_CONTENT", "원하는 콘텐츠나 기능의 부족"),
                            ("OTHER", "기타"),
                        ],
                        max_length=30,
                        verbose_name="탈퇴 사유",
                    ),
                ),
                ("reason_detail", models.DateField(verbose_name="구체적인 탈퇴 사유")),
                ("due_date", models.DateField(verbose_name="계정 삭제 예정일")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name="유저"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
