# Generated by Django 5.2.1 on 2025-09-02 05:12

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_withdrwals_reason_detail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="provider",
            field=models.CharField(
                choices=[("KAKAO", "카카오"), ("NAVER", "네이버")], help_text="소셜 로그인 제공 업체", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="provider_id",
            field=models.CharField(help_text="소셜 로그인 업체 고유 ID", max_length=255),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="user",
            field=models.ForeignKey(
                help_text="유저", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(help_text="생일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="email address", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(help_text="성별", max_length=6),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False, help_text="계정활성화 여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False, help_text="스태프 여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_superuser",
            field=models.BooleanField(default=False, help_text="슈퍼 유저 여부"),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(help_text="이름", max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(help_text="닉네임", max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(help_text="휴대폰 번호", max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_img_url",
            field=models.URLField(blank=True, help_text="프로필 이미지", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUID", unique=True),
        ),
        migrations.AlterField(
            model_name="withdrwals",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="생성일시"),
        ),
        migrations.AlterField(
            model_name="withdrwals",
            name="due_date",
            field=models.DateField(help_text="계정 삭제 예정일"),
        ),
        migrations.AlterField(
            model_name="withdrwals",
            name="reason",
            field=models.CharField(
                choices=[
                    ("NO_LONGER_NEEDED", "서비스 이용할 시간이 없음"),
                    ("LACK_OF_INTEREST", "관심이 사라짐"),
                    ("TOO_DIFFICULT", "서비스를 이용하기가 너무 어려움"),
                    ("FOUND_BETTER_SERVICE", "더 좋은 대안을 찾음"),
                    ("PRIVACY_CONCERNS", "개인정보/보안/우려"),
                    ("POOR_SERVICE_QUALITY", "서비스 품질 불만"),
                    ("TECHNICAL_ISSUES", "기술적문제(버그 등)"),
                    ("LACK_OF_CONTENT", "원하는 콘텐츠나 기능의 부족"),
                    ("OTHER", "기타"),
                ],
                help_text="탈퇴 사유",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="withdrwals",
            name="reason_detail",
            field=models.CharField(help_text="구체적인 탈퇴 사유", max_length=500),
        ),
        migrations.AlterField(
            model_name="withdrwals",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, help_text="수정 일시", null=True),
        ),
        migrations.AlterField(
            model_name="withdrwals",
            name="user",
            field=models.OneToOneField(
                help_text="유저", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
