# Generated by Django 5.2.1 on 2025-09-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_socialuser_withdrwals"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrwals",
            name="uuid",
        ),
        migrations.AlterField(
            model_name="withdrwals",
            name="id",
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
