# Generated by Django 5.2.1 on 2025-09-04 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_socialuser_created_at_alter_socialuser_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Withdrwals",
            new_name="Withdrawals",
        ),
    ]
