# Generated by Django 5.2.1 on 2025-09-09 04:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_withdrwals_withdrawals"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawals",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUID", unique=True),
        ),
    ]
