# Generated by Django 5.2.1 on 2025-09-09 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_withdrawals_uuid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="withdrawals",
            name="uuid",
        ),
    ]
