# Generated by Django 5.2.1 on 2025-09-24 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_withdrawals_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(help_text="닉네임", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, help_text="휴대폰 번호", max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="withdrawals",
            name="user",
            field=models.OneToOneField(
                help_text="유저", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
