# Generated by Django 5.2.1 on 2025-09-24 04:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_withdrawals_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, help_text="생일", null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, help_text="email address", max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(blank=True, help_text="성별", max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(blank=True, help_text="이름", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, help_text="닉네임", max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, help_text="휴대폰 번호", max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="withdrawals",
            name="user",
            field=models.OneToOneField(
                help_text="유저", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
