# Generated by Django 5.2.1 on 2025-09-02 08:48

import apps.recruitments.models.recruitments
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studies", "0002_alter_groupmember_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                ("name", models.CharField(help_text="태그명", max_length=20)),
            ],
            options={
                "db_table": "tags",
            },
        ),
        migrations.CreateModel(
            name="Recruitment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, help_text="UUID", unique=True)),
                ("title", models.CharField(help_text="공고 제목", max_length=50)),
                ("content", models.TextField(help_text="공고 내용")),
                ("estimated_fee", models.IntegerField(help_text="예상 강의 결제 비용")),
                (
                    "expected_headcount",
                    models.SmallIntegerField(
                        help_text="예상 모집 인원",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                ("views_count", models.IntegerField(default=0, help_text="조회수")),
                (
                    "close_at",
                    models.DateTimeField(
                        default=apps.recruitments.models.recruitments.Recruitment.get_default_close_at,
                        help_text="공고 마감일",
                    ),
                ),
                ("is_closed", models.BooleanField(default=False, help_text="공고 마감 상태")),
                (
                    "author_id",
                    models.ForeignKey(
                        help_text="공고 작성자 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authored_recruitments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group_id",
                    models.ForeignKey(
                        help_text="스터디 그룹 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitments",
                        to="studies.studygroup",
                    ),
                ),
            ],
            options={
                "db_table": "recruitments",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                ("file_url", models.CharField(help_text="첨부파일 URL", max_length=255, unique=True)),
                ("file_name", models.CharField(help_text="원본 파일명", max_length=50)),
                (
                    "recruitment_id",
                    models.ForeignKey(
                        help_text="스터디 공고 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_attachments",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentBookmark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "recruitment_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recruitment_id",
                    models.ForeignKey(
                        help_text="공고 ID", on_delete=django.db.models.deletion.CASCADE, to="recruitments.recruitment"
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="북마크한 유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_bookmarks",
            },
        ),
        migrations.AddField(
            model_name="recruitment",
            name="bookmarks",
            field=models.ManyToManyField(
                related_name="bookmarked_recruitments",
                through="recruitments.RecruitmentBookmark",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RecruitmentImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                ("img_url", models.CharField(help_text="이미지 URL", max_length=255, unique=True)),
                (
                    "recruitment_id",
                    models.ForeignKey(
                        help_text="스터디 공고 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="recruitments.recruitment",
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_images",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentSearchLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                ("keyword", models.CharField(help_text="검색어", max_length=255)),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="유저 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recruitment_search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_search_logs",
            },
        ),
        migrations.CreateModel(
            name="RecruitmentTag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "recruitment_id", "tag_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "recruitment_id",
                    models.ForeignKey(
                        help_text="공고 ID", on_delete=django.db.models.deletion.CASCADE, to="recruitments.recruitment"
                    ),
                ),
                (
                    "tag_id",
                    models.ForeignKey(
                        help_text="태그 ID", on_delete=django.db.models.deletion.CASCADE, to="recruitments.tag"
                    ),
                ),
            ],
            options={
                "db_table": "recruitment_tags",
            },
        ),
        migrations.AddField(
            model_name="recruitment",
            name="tags",
            field=models.ManyToManyField(
                related_name="recruitments", through="recruitments.RecruitmentTag", to="recruitments.tag"
            ),
        ),
        migrations.AddConstraint(
            model_name="recruitment",
            constraint=models.CheckConstraint(
                condition=models.Q(("expected_headcount__gte", 1), ("expected_headcount__lte", 10)),
                name="recruitment_expected_headcount_range_1_10",
            ),
        ),
    ]
