# Generated by Django 5.2.1 on 2025-09-02 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recruitmentattachment",
            name="file_url",
            field=models.URLField(help_text="첨부파일 URL", max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="recruitmentimage",
            name="img_url",
            field=models.URLField(help_text="이미지 URL", max_length=255, unique=True),
        ),
    ]
