# Generated by Django 5.2.1 on 2025-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0002_alter_recruitmentattachment_file_url_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruitment",
            old_name="author_id",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="recruitment",
            old_name="study_group_id",
            new_name="study_group",
        ),
        migrations.RenameField(
            model_name="recruitmentattachment",
            old_name="recruitment_id",
            new_name="recruitment",
        ),
        migrations.RenameField(
            model_name="recruitmentbookmark",
            old_name="recruitment_id",
            new_name="recruitment",
        ),
        migrations.RenameField(
            model_name="recruitmentbookmark",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="recruitmentimage",
            old_name="recruitment_id",
            new_name="recruitment",
        ),
        migrations.RenameField(
            model_name="recruitmentsearchlog",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="recruitmenttag",
            old_name="recruitment_id",
            new_name="recruitment",
        ),
        migrations.RenameField(
            model_name="recruitmenttag",
            old_name="tag_id",
            new_name="tag",
        ),
        migrations.AlterField(
            model_name="recruitmentbookmark",
            name="pk",
            field=models.CompositePrimaryKey(
                "user", "recruitment", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="recruitmenttag",
            name="pk",
            field=models.CompositePrimaryKey(
                "recruitment", "tag", blank=True, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
