# Generated by Django 5.2.1 on 2025-09-02 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0003_rename_author_id_recruitment_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="recruitment",
            old_name="bookmarks",
            new_name="bookmark_users",
        ),
    ]
