# Generated by Django 5.2.1 on 2025-09-03 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0004_rename_bookmarks_recruitment_bookmark_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(help_text="태그명", max_length=20, unique=True),
        ),
    ]
