# Generated by Django 5.2.1 on 2025-09-27 14:17

from django.db import migrations

TAGS = [
    "Python",
    "React",
    "TypeScript",
    "Spring",
    "Django",
    "Vue.js",
    "Angular",
    "Node.js",
    "Express",
    "MongoDB",
    "SQL",
    "Java",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "Machine Learning",
    "Data Science",
    "AI",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "GCP",
    "Front-end",
    "Back-end",
    "Full-stack",
    "iOS",
    "Android",
    "초보자환영",
    "주말스터디",
    "온라인",
    "오프라인",
    "스터디",
    "프로젝트",
    "디자인",
    "UX/UI",
    "Figma",
    "Photoshop",
    "Illustrator",
    "HTML",
    "CSS",
    "JavaScript",
    "Git",
    "Scrum",
    "Agile",
    "Jira",
    "피그마",
]


def seed_tags(apps, schema_editor):
    """
    초기 태그 데이터를 생성합니다.
    """
    Tag = apps.get_model("recruitments", "Tag")
    for tag_name in TAGS:
        Tag.objects.get_or_create(name=tag_name)


def revert_tags(apps, schema_editor):
    """
    초기 태그 데이터를 삭제합니다.
    """
    Tag = apps.get_model("recruitments", "Tag")
    Tag.objects.filter(name__in=TAGS).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("recruitments", "0005_alter_tag_name"),
    ]

    operations = [
        migrations.RunPython(seed_tags, reverse_code=revert_tags),
    ]
