# Generated by Django 5.2.1 on 2025-09-02 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recruitments", "0002_alter_recruitmentattachment_file_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                ("objective", models.CharField(help_text="목표", max_length=300)),
                ("motivation", models.TextField(help_text="지원동기")),
                ("self_introduction", models.TextField(help_text="자기소개")),
                ("available_time", models.CharField(help_text="가능한 시간대와 요일", max_length=255)),
                ("has_study_experience", models.BooleanField(default=False, help_text="과거 스터디 경험 여부")),
                ("study_experience", models.TextField(blank=True, help_text="스터디 경험", null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("CANCELED", "취소됨"),
                            ("ACCEPTED", "승인됨"),
                            ("REJECTED", "거절됨"),
                        ],
                        default="PENDING",
                        help_text="공고 지원 상태",
                        max_length=20,
                    ),
                ),
                (
                    "recruitment_id",
                    models.ForeignKey(
                        help_text="지원한 공고의 ID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="recruitments.recruitment",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        help_text="지원한 사용자 ID",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "applications",
                "constraints": [
                    models.UniqueConstraint(fields=("recruitment_id", "user_id"), name="UQ_recruitments_users_IDX")
                ],
            },
        ),
    ]
