# Generated by Django 5.2.1 on 2025-09-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="motivation",
            field=models.CharField(help_text="지원동기", max_length=500),
        ),
        migrations.AlterField(
            model_name="application",
            name="self_introduction",
            field=models.CharField(help_text="자기소개", max_length=500),
        ),
        migrations.AlterField(
            model_name="application",
            name="study_experience",
            field=models.CharField(blank=True, help_text="스터디 경험", max_length=1000, null=True),
        ),
    ]
