# Generated by Django 5.2.1 on 2025-09-02 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_alter_application_motivation_and_more"),
        ("recruitments", "0003_rename_author_id_recruitment_author_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="application",
            name="UQ_recruitments_users_IDX",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="recruitment_id",
            new_name="recruitment",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddConstraint(
            model_name="application",
            constraint=models.UniqueConstraint(fields=("recruitment", "user"), name="UQ_recruitments_users_IDX"),
        ),
    ]
