# Generated by Django 5.2.1 on 2025-09-26 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_remove_application_uq_recruitments_users_idx_and_more"),
        ("recruitments", "0005_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="recruitment",
            field=models.ForeignKey(
                help_text="지원한 공고의 ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="recruitments.recruitment",
            ),
        ),
    ]
