class EmailSendingFailedError(Exception): ...


class EmailVerificationCodeFailedError(Exception): ...


class PhoneSendingFailedError(Exception): ...


class PhoneVerificationCodeFailedError(Exception): ...
