# Generated by Django 5.2.1 on 2025-09-01 09:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "verbose_name": "강의 카테고리",
                "verbose_name_plural": "강의 카테고리 목록",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="UUID")),
                ("title", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=20)),
                ("average_rating", models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ("duration", models.SmallIntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "쉬움"), ("normal", "보통"), ("hard", "어려움")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("platform", models.CharField(choices=[("udemy", "유데미"), ("inflearn", "인프런")], max_length=10)),
                ("original_price", models.BigIntegerField(default=0)),
                ("discount_price", models.BigIntegerField(default=0)),
                ("url_link", models.CharField(max_length=255)),
                ("thumbnail_img_url", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "verbose_name": "크롤링 강의",
                "verbose_name_plural": "크롤링 강의 목록",
                "db_table": "crawled_lectures",
            },
        ),
        migrations.CreateModel(
            name="LectureBookmark",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "lecture_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("lecture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.lecture")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "강의 북마크",
                "verbose_name_plural": "강의 북마크 목록",
                "db_table": "lecture_bookmarks",
            },
        ),
        migrations.CreateModel(
            name="LectureCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "lecture_id", "category_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.category")),
                ("lecture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.lecture")),
            ],
            options={
                "verbose_name": "강의 카테고리",
                "verbose_name_plural": "강의 카테고리 목록",
                "db_table": "lecture_categories",
            },
        ),
        migrations.AddField(
            model_name="lecture",
            name="categories",
            field=models.ManyToManyField(
                related_name="lectures", through="lectures.LectureCategory", to="lectures.category"
            ),
        ),
        migrations.CreateModel(
            name="LectureReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("5_OUT_OF_5_STARS", "별점 5점"),
                            ("4_OUT_OF_5_STARS", "별점 4점"),
                            ("3_OUT_OF_5_STARS", "별점 3점"),
                            ("2_OUT_OF_5_STARS", "별점 2점"),
                            ("1_OUT_OF_5_STARS", "별점 1점"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="lectures.lecture"
                    ),
                ),
            ],
            options={
                "verbose_name": "크롤링 강의 리뷰",
                "verbose_name_plural": "크롤링 강의 리뷰 목록",
                "db_table": "crawled_lecture_reviews",
            },
        ),
        migrations.CreateModel(
            name="LectureSearchLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                ("keyword", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "강의 검색 기록",
                "verbose_name_plural": "강의 검색 기록 목록",
                "db_table": "lecture_search_logs",
            },
        ),
        migrations.CreateModel(
            name="UserPreferCategory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, null=True, verbose_name="수정 일시")),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "user_id", "category_id", blank=True, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.category")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "사용자 선호 카테고리",
                "verbose_name_plural": "사용자 선호 카테고리 목록",
                "db_table": "user_prefer_categories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="lecture",
            unique_together={("platform", "title")},
        ),
    ]
