# Generated by Django 5.2.1 on 2025-09-01 08:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "강의 카테고리",
                "verbose_name_plural": "강의 카테고리 목록",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="LectureSearchLogModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("keyword", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "강의 검색 기록",
                "verbose_name_plural": "강의 검색 기록 목록",
                "db_table": "lecture_search_logs",
            },
        ),
        migrations.CreateModel(
            name="LectureCategoryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.categorymodel"),
                ),
            ],
            options={
                "verbose_name": "강의 카테고리",
                "verbose_name_plural": "강의 카테고리 목록",
                "db_table": "lecture_categories",
            },
        ),
        migrations.CreateModel(
            name="LectureModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("instructor", models.CharField(max_length=20)),
                ("average_rating", models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ("duration", models.SmallIntegerField()),
                (
                    "difficulty",
                    models.CharField(
                        choices=[("easy", "쉬움"), ("normal", "보통"), ("hard", "어려움")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("description", models.TextField()),
                ("platform", models.CharField(choices=[("udemy", "유데미"), ("inflearn", "인프런")], max_length=10)),
                ("original_price", models.BigIntegerField(default=0)),
                ("discount_price", models.BigIntegerField(default=0)),
                ("url_link", models.CharField(max_length=255)),
                ("thumbnail_img_url", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="lectures", through="lectures.LectureCategoryModel", to="lectures.categorymodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "크롤링 강의",
                "verbose_name_plural": "크롤링 강의 목록",
                "db_table": "crawled_lectures",
                "unique_together": {("platform", "title")},
            },
        ),
        migrations.AddField(
            model_name="lecturecategorymodel",
            name="lecture",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.lecturemodel"),
        ),
        migrations.CreateModel(
            name="LectureBookmarkModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("lecture", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.lecturemodel")),
            ],
            options={
                "verbose_name": "강의 북마크",
                "verbose_name_plural": "강의 북마크 목록",
                "db_table": "lecture_bookmarks",
            },
        ),
        migrations.CreateModel(
            name="LectureReviewModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("5_OUT_OF_5_STARS", "별점 5점"),
                            ("4_OUT_OF_5_STARS", "별점 4점"),
                            ("3_OUT_OF_5_STARS", "별점 3점"),
                            ("2_OUT_OF_5_STARS", "별점 2점"),
                            ("1_OUT_OF_5_STARS", "별점 1점"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="lectures.lecturemodel"
                    ),
                ),
            ],
            options={
                "verbose_name": "크롤링 강의 리뷰",
                "verbose_name_plural": "크롤링 강의 리뷰 목록",
                "db_table": "crawled_lecture_reviews",
            },
        ),
        migrations.CreateModel(
            name="UserPreferCategoryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="lectures.categorymodel"),
                ),
            ],
            options={
                "verbose_name": "사용자 선호 카테고리",
                "verbose_name_plural": "사용자 선호 카테고리 목록",
                "db_table": "user_prefer_categories",
            },
        ),
        migrations.AlterUniqueTogether(
            name="lecturecategorymodel",
            unique_together={("lecture", "category")},
        ),
    ]
