# Generated by Django 5.2.1 on 2025-09-01 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AlterModelOptions(
            name="lecture",
            options={},
        ),
        migrations.AlterModelOptions(
            name="lecturebookmark",
            options={},
        ),
        migrations.AlterModelOptions(
            name="lecturecategory",
            options={},
        ),
        migrations.AlterModelOptions(
            name="lecturereview",
            options={},
        ),
        migrations.AlterModelOptions(
            name="lecturesearchlog",
            options={},
        ),
        migrations.AlterModelOptions(
            name="userprefercategory",
            options={},
        ),
        migrations.AlterUniqueTogether(
            name="lecture",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="thumbnail_img_url",
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="url_link",
            field=models.URLField(max_length=255),
        ),
    ]
