# Generated by Django 5.2.1 on 2025-09-01 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_alter_category_options_alter_lecture_options_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lecture",
            unique_together={("platform", "title")},
        ),
    ]
