# Generated by Django 5.2.1 on 2025-09-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0004_alter_category_created_at_alter_category_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="thumbnail_img_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="url_link",
            field=models.URLField(max_length=500),
        ),
    ]
