# Generated by Django 5.2.1 on 2025-09-09 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0005_alter_lecture_thumbnail_img_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="url_link",
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
