# Generated by Django 5.2.1 on 2025-09-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0006_alter_lecture_description_alter_lecture_url_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecturereview",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
