# Generated by Django 5.2.1 on 2025-09-02 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                ("content", models.CharField(max_length=300)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("STUDY_JOIN", "스터디 참여"),
                            ("STUDY_NOTE_CREATE", "스터디 기록 작성"),
                            ("STUDY_REVIEW_REQUEST", "스터디 후기 요청"),
                            ("APPLICATION_ACCEPT", "지원 수락"),
                            ("APPLICATION_REJECT", "지원 거절"),
                            ("ADD_APPLICATION", "신규 지원"),
                            ("TODAY_SCHEDULE", "오늘의 스케줄"),
                            ("UPCOMING_SCHEDULE", "임박한 스케줄"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("back_url_link", models.URLField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notifications",
                "ordering": ["-created_at"],
            },
        ),
    ]
