# Generated by Django 5.2.1 on 2025-09-02 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("studies", "0002_alter_groupmember_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, help_text="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, help_text="수정 일시", null=True)),
                ("content", models.CharField(max_length=500)),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "study_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="studies.studygroup",
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["study_group", "-created_at"], name="chat_messag_study_g_eb40d0_idx")],
            },
        ),
    ]
