# Generated by Django 5.2.1 on 2025-09-23 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_lastreadmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lastreadmessage",
            old_name="message",
            new_name="message_id",
        ),
    ]
