# Generated by Django 5.2.1 on 2025-09-23 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_rename_message_lastreadmessage_message_id"),
        ("studies", "0002_alter_groupmember_created_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="lastreadmessage",
            index=models.Index(fields=["study_group", "user"], name="last_group__study_g_4ff8b2_idx"),
        ),
    ]
